function stReg = ep_ec_registry_hooks_get()
% Returns all known hooks and the corresponding default value function.
%
% stReg = ep_ec_registry_hooks_get()
%
%  OUTPUT            DESCRIPTION
%
%  - stReg          The known hooks with their default value function
%

%%
stReg = struct( ...
    'ecahook_autosar_wrapper_function_info', 'ep_ec_ecahook_autosar_wrapper_function_info_config_get', ...
    'ecahook_simulationtime_get_fun',        'ep_ec_ecahook_simulationtime_get_fun_config_get', ...
    'ecahook_legacy_code',                   'ep_ec_ecahook_legacy_code_config_get', ...
    'ecahook_ignore_code',                   'ep_ec_ecahook_ignore_code_config_get', ...
    'ecahook_param_blacklist',               'ep_ec_ecahook_param_blacklist_config_get', ...
    'ecahook_stub_include_files',            'ep_ec_ecahook_stub_include_files_config_get',...
    'ecahook_post_analysis',                 '', ...
    'ecahook_pre_analysis',                  '', ...
    'ecahook_post_wrapper_create',           '');
end