function stResult = ut_ec_model_analyse_sl_sil(xEnv, sModelFile, sInitScript, sResultDir, stOverrideArgs)
if (nargin == 4)
    stOverrideArgs = struct();
end

stArgs = ut_get_ec_args(xEnv, sModelFile, sInitScript, sResultDir, stOverrideArgs);
stArgs.AddCodeModel = 'no'; % !!! main flag for triggering SL SIL analysis
[stModel, astModules] = ep_ec_model_info_get(xEnv, stArgs);
xEnv.exportMessages(stArgs.MessageFile);

% --- result ----------
stResult = struct( ...
    'sAddModelInfo',     stArgs.AddModelInfoFile, ...
    'sSlArch',           stArgs.SlArchFile, ...
    'sMapping',          stArgs.MappingFile, ...
    'sCodeModel',        stArgs.CodeModelFile, ...
    'sConstantsFile',    stArgs.ConstantsFile, ...
    'sMessages',         stArgs.MessageFile, ...
    'stModel',           stModel, ...
    'astModules',        astModules);
end
