function sException = tu_exception_struct_convert(stException)
% Convert an exception structure into a single string representation
%
% function sException = tu_exception_struct_convert(stException)
%
%   INPUT              DESCRIPTION
%     stException       (struct)   Structure that was generated by
%                                  'lasterror'-function.
%                                  Assumed fields:
%                                    -stException.identifier
%                                    -stException.message
%                                    -stException.stack.file
%                                    -stException.stack.line
% 
%   OUTPUT              DESCRIPTION
%     sException        (string)   String representation that contains all
%                                  the information of the exception struct
% 
%  <et_copyright>

%% internal 
%
%   REFERENCE(S):
%
%   RELATED MODULES:
%
%   AUTHOR(S):
%     Stefan Schulz
% $$$COPYRIGHT$$$
%

%%
casFile = {stException.stack.file};
casLine = {stException.stack.line};

casStackInfo = strcat(casFile', ...
    repmat(', line:', length(casFile), 1), ...
    cellfun(@int2str, casLine', 'UniformOutput', false), ...
    repmat(';', length(casFile), 1));

sStackInfo = strrep([casStackInfo{:}], ';' , char(10));

sException = sprintf('Id: %s\nMessage: %s\nStack:\n%s', ...
    stException.identifier, stException.message, sStackInfo);
end

