function utclean
% Remove all automatically created unit test files.

%%  remove files
files = { ...
        'MUnit-List.dtd', ...
        'MUnit-Run.xsl', ...
        'index.html', ... 
        'index_for_dev.html', ... 
        'MUnit-List.xsl', ...
        'UnitTest-Listing.xml', ...
        'UnitTest-Listing.html', ...
        'MUnit-Run.dtd', ...
        'UnitTest-Results.xml', ...
        'UnitTest-Results.html', ...
        'menu.xhtml'};

for i = 1:length(files)
    if exist([cd, '\', files{i}], 'file')
        delete(files{i});
    end
end

%  remove coverage statistics
if isdir('mcovreport')
    rmdir('mcovreport', 's');
end
end