function sltu_activate_java_resources
% Executing this function enables the execution of Matlab UTs directly inside the Matlab console.
%


%%
casNeededJarNames = { ...
    'ep.ats.models', ...
    'ep.ats.models.dev.c', ...
    'ep.ats.models.dev.ec', ...
    'ep.ats.models.dev.sl', ...
    'ep.ats.models.dev.tl', ...
    ... % 'ep.ats.models.featuretest', ...
    ... % 'ep.ats.models.customer', ...
    'ep.architecture.spec', ...
    'ep.architecture.spec.test.utils'};
ep_ats_ut_enable(casNeededJarNames);
end




