function stCodeInfo = getCodeInfoDefault(~)

stCodeInfo = struct( ...
    'sCFunctionName',               '', ...
    'sInitCFunctionName',           '', ...
    'sPreStepCFunctionName',        '', ...
    'sCFunctionUpdateName',         '', ...
    'sCFunctionDefinitionFileName', '', ...
    'sCFunctionDefinitionFile',     '', ...
    'sEPCFunctionPath',             '', ...
    'bHasFuncArgs',                 false);
end
