function ep_sl_enable_logging(xEnv, stSrcModelInfo, stExtrModelInfo, stArgs)
bSelfContained = stArgs.BreakLinks && (stArgs.ModelRefMode ~= ep_sl.Constants.KEEP_REFS);
if bSelfContained || strcmp(stArgs.OriginalSimulationMode, 'SL SIL') % needed for logging of SL SIL on MAPI
    stEnv = ep_core_legacy_env_get(xEnv, true);
    bTLSilMode  = false;
    bBreakModelRefs = stArgs.ModelRefMode == ep_sl.Constants.BREAK_REFS;
    atgcv_mil_model_logging(...
        stEnv, ...
        stSrcModelInfo.xSubsys, ...
        stSrcModelInfo.nUsage, ...
        stExtrModelInfo.sName, ...
        stArgs.EnableSubsystemLogging, ...
        bTLSilMode, ...
        bBreakModelRefs, ...
        []);
    
    % Can be shifted to atgcv_mil_model_logging or a different method if TL use case are also shifted to the new
    % behaviour
    set_param(stExtrModelInfo.hModel, 'SignalLoggingSaveFormat', 'Dataset'); %see EPDEV-51950
end
end