function ep_sl_enable_calibration(xEnv, stSrcModelInfo, stExtrModelInfo, stArgs)
stEnv = ep_core_legacy_env_get(xEnv, true);
i_pre_sim_script_gen(stEnv, stSrcModelInfo, stExtrModelInfo, stArgs);
end

%%
function i_pre_sim_script_gen(stEnv, stSrcModelInfo, stExtrModelInfo, stArgs)
ep_sim_sl_pre_sim_script_gen(stEnv, ...
    stExtrModelInfo.sName, ...
    stSrcModelInfo.xSubsys, ...
    stSrcModelInfo.nUsage, ...
    stArgs.ModelRefMode, ...
    []);
end