function astSignals = atgcv_m01_block_output_signals_memget(stEnv, hBlock, iPortNumber, bWithVarInfo)
% Memoized version of the original atgcv_m01_block_output_signals_get

persistent p_stCache;

if (isempty(p_stCache) ...
        || p_stCache.hBlock ~= hBlock ...
        || p_stCache.iPortNumber ~= iPortNumber ...
        || p_stCache.bWithVarInfo ~= bWithVarInfo)
    
    % cache miss: need to recompute the signals for the block
    astSignals = atgcv_m01_block_output_signals_get(stEnv, hBlock, iPortNumber, bWithVarInfo);
        
    p_stCache = struct( ...
        'hBlock',       hBlock, ...
        'iPortNumber',  iPortNumber, ...
        'bWithVarInfo', bWithVarInfo, ...
        'astSignals',   astSignals);
end
astSignals = p_stCache.astSignals;
end

