function it_slmil_derive_bus()
% Checks the derived test vectors

casScopeID  = {'260'};
sOrgSimMode = 'SL MIL';

[oOnCleanUpCloseModel, stTestData] = sltu_prepare_simenv(...
    'BusPorts', ...
    'SL', ...
    'busports_toplevel', ...
    'derive_bus', ...
    [], ...
    casScopeID);

stExtractInfo = sltu_extract_model(...
    stTestData, ...
    'OriginalSimulationMode', sOrgSimMode, ...
    'EnableSubsystemLogging', true);

oOnCleanUpCloseExtrModel = sltu_derive_model(...
    stTestData, ...
    stExtractInfo, ...
    'ExecutionMode', sOrgSimMode);
oCleanupTestEnv = onCleanup(@() cellfun(@delete, {oOnCleanUpCloseModel, oOnCleanUpCloseExtrModel}));

if ep_core_version_compare('ML9.6') < 0
    SLTU_ASSERT_DERIVED_VECTOR(stTestData);
else
    SLTU_ASSERT_DERIVED_VECTOR(stTestData, 'ml2019a');
end
end
