function it_slmil_derive_matrix()
% Checks the derived test vectors

casScopeID  = {'2Cl'};
sOrgSimMode = 'SL MIL';

[oOnCleanUpCloseModel, stTestData] = sltu_prepare_simenv(...
    'Matrix', ...
    'SL', ...
    'matrix_complex1', ...
    'matrix_derive', ...
    [], ...
    casScopeID);

stExtractInfo = sltu_extract_model(...
    stTestData, ...
    'OriginalSimulationMode', sOrgSimMode, ...
    'EnableSubsystemLogging', true);

oOnCleanUpCloseExtrModel = sltu_derive_model(...
    stTestData, ...
    stExtractInfo, ...
    'ExecutionMode', sOrgSimMode);
oCleanupTestEnv = onCleanup(@() cellfun(@delete, {oOnCleanUpCloseModel, oOnCleanUpCloseExtrModel}));

SLTU_ASSERT_DERIVED_VECTOR(stTestData);
end