function it_slmil_derive_pw_pwc()
% Checks the derived test vectors

casScopeID  = {'285', '286'};
sOrgSimMode = 'SL MIL';

[oOnCleanUpCloseModel, stTestData] = sltu_prepare_simenv(...
    'PowerWindowSimple', ...
    'SL', ...
    'pw_pwc', ...
    'pwc', ...
    [], ...
    casScopeID);

stExtractInfo = sltu_extract_model(...
    stTestData, ...
    'OriginalSimulationMode', sOrgSimMode, ...
    'EnableSubsystemLogging', true);

oOnCleanUpCloseExtrModel = sltu_derive_model(...
    stTestData, ...
    stExtractInfo, ...
    'ExecutionMode', sOrgSimMode);
oCleanupTestEnv = onCleanup(@() cellfun(@delete, {oOnCleanUpCloseModel, oOnCleanUpCloseExtrModel}));

SLTU_ASSERT_DERIVED_VECTOR(stTestData);
end
