function it_slmil_derive_dsm_matrix()
% Checks the derived test vectors

casScopeID  = {'2CG'};
sOrgSimMode = 'SL MIL';

[oOnCleanUpCloseModel, stTestData] = sltu_prepare_simenv(...
    'DataStoreMemory', ...
    'SL', ...
    'dsm_matrix_in', ...
    'top', ...
    [], ...
    casScopeID);

stExtractInfo = sltu_extract_model(...
    stTestData, ...
    'OriginalSimulationMode', sOrgSimMode, ...
    'EnableSubsystemLogging', true);

oOnCleanUpCloseExtrModel = sltu_derive_model(...
    stTestData, ...
    stExtractInfo, ...
    'ExecutionMode', sOrgSimMode);
oCleanupTestEnv = onCleanup(@() cellfun(@delete, {oOnCleanUpCloseModel, oOnCleanUpCloseExtrModel}));

SLTU_ASSERT_DERIVED_VECTOR(stTestData);
end
