function it_slmil_derive_stateflow()
% Checks the derived test vectors

casScopeID  = {'2Np'};
sOrgSimMode = 'SL MIL';

[oOnCleanUpCloseModel, stTestData] = sltu_prepare_simenv(...
    'ManyLocals', ...
    'SL', ...
    'locals_stateflow', ...
    'derive_stateflow', ...
    [], ...
    casScopeID);

stExtractInfo = sltu_extract_model(...
    stTestData, ...
    'OriginalSimulationMode', sOrgSimMode, ...
    'EnableSubsystemLogging', true);

oOnCleanUpCloseExtrModel = sltu_derive_model(...
    stTestData, ...
    stExtractInfo, ...
    'ExecutionMode', sOrgSimMode);
oCleanupTestEnv = onCleanup(@() cellfun(@delete, {oOnCleanUpCloseModel, oOnCleanUpCloseExtrModel}));

SLTU_ASSERT_DERIVED_VECTOR(stTestData);
end
