function utclean
% Remove all automatically created unit test files.
%
% function utclean
%

%  remove files
files = { ...
        'MUnit-List.dtd', ...
        'MUnit-Run.xsl', ...
        'index.html', ... 
        'MUnit-List.xsl', ...
        'UnitTest-Listing.xml', ...
        'MUnit-Run.dtd', ...
        'UnitTest-Results.xml', ...
        'menu.xhtml', ...
    };

for i=1:length(files)
    if exist([cd, '\', files{i}], 'file')
        delete(files{i});
    end
end

%  remove coverage statistics
if isdir('mcovreport')
    dos('rmdir /S /Q "mcovreport"');
end
end
